version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.9.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

  test:
    docker:
      - image: circleci/python:3.9.4

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: test
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
            python3 -m unittest test
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "test.py" }}
          
  
  
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      # - test
      
